name: com.rado.quick_mart
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  internet_connection_checker: ^1.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  curved_navigation_bar: ^1.0.3
  flutter_email_sender: ^6.0.2
  cached_network_image: ^3.3.0
  flutter_masonry_view: ^0.0.2
  firebase_database: ^10.3.8
  flutter_screenutil: ^5.9.0
  firebase_storage: ^11.5.6
  dropdown_button2: ^2.3.9
  cloud_firestore: ^4.13.6
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter_offline: ^3.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  awesome_icons: ^1.1.0
  fluttertoast: ^8.2.4
  image_picker: ^1.0.5
  url_launcher: ^6.2.2
  connectivity: ^3.0.6
  photo_view: ^0.14.0
  readmore: ^2.2.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  mailer: ^6.0.1
  intl: ^0.18.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoImage.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/jsons/
  fonts:
    - family: Times
      fonts:
        - asset: assets/fonts/timesFont.ttf
    - family: Elora
      fonts:
        - asset: assets/fonts/eloraFont.otf